Add menu bar for future frameless mode, add attempt quit with dialog …
vircadia/pantheon-launcher pull request #12
Opened 2020-03-19 00:12 UTC by kasenvr

…if interface running.

2020-03-19 00:25 UTC, Nex-Pro commented
@kasenvr can we get a name for the color on line 14 of App.vue ?

2020-03-19 00:27 UTC, Nex-Pro commented
https://www.colorhexa.com/182b49

2020-03-19 00:34 UTC, kasenvr commented
Do you mean to use a name instead of a hex? I scrolled through the list of CSS names detected by Chrome and none of them really came close to this color sadly.

2020-03-19 23:48 UTC, Nex-Pro commented
Even put a descriptive comment might be good. HiFi named colors. It saves having the reader try to work out what the color is if it has a name or a description.

2020-03-20 07:27 UTC, ctrlaltdavid commented
README.md needs updating with instructions on how to install tasklist module.

2020-03-20 07:37 UTC, ctrlaltdavid requested changes

2020-03-20 07:37 UTC, ctrlaltdavid commented on src/components/Dialogs/WantToClose.vue
> +//  Created by David Rowe on 14 Feb 2020.
No I didn't.

2020-03-20 07:37 UTC, ctrlaltdavid commented on src/components/Dialogs/WantToClose.vue
> +            // nothing to do.
```suggestion
            // Nothing to do.
```

2020-03-20 07:37 UTC, ctrlaltdavid commented on src/components/Dialogs/WantToClose.vue
> +</script>
Missing new line at end of file.

2020-03-28 07:58 UTC, ctrlaltdavid approved these changes

2020-03-28 08:13 UTC, merged