Feature/update dialog
vircadia/pantheon-launcher pull request #13
Opened 2020-03-28 06:15 UTC by kasenvr

This adds an update dialog and renames the launcher in most places, if not all. But it needs further testing to confirm... some odd artifacts with the naming I saw but can't tell why.

2020-03-28 08:14 UTC, ctrlaltdavid requested changes

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/App.vue
> +                    v-if="showDownloadButton"
Indenting weird because of surrounding lines using tabs.

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/App.vue
> +                    <span style="font-size: 12px;">Check for Updates</span>
Should the styling be in the CSS file rather than inline?

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/App.vue
> +            // This function also auto-installs interface.
Indenting / tabs.

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/App.vue
> +		interfaceSelected() {
Tabs

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/background.js
> +	var vircadiaMetaFile = storagePath.default + '/athenaMeta.json';
athenaMeta.json should be renamed to vircadiaMeta.json?

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/background.js
> +		console.info("Athena Meta JSON:", vircadiaMetaJSON);
"Athena" occurrence.

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/background.js
>          console.error("Failed to download Athena Meta JSON");
"Athena" occurrence.

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/background.js
>  	event.returnValue = athenaLocationExe;
"Athena" occurrences.

2020-03-28 08:14 UTC, ctrlaltdavid commented on src/background.js
>  			if(results) {
Tabs

2020-04-01 22:41 UTC, kasenvr commented
Currently, this does not kick in unless there's an interface selected.

2020-04-04 03:28 UTC, ctrlaltdavid requested changes

2020-04-04 03:28 UTC, ctrlaltdavid commented on src/components/Dialogs/WantToClose.vue
> +//  Copyright 2020 Project Athena and contributors.
```suggestion
//  Copyright 2020 Vircadia and contributors.
```

2020-04-04 03:28 UTC, ctrlaltdavid commented on public/css/styles.css
> +}
Add CR to end of file.

2020-04-04 03:28 UTC, ctrlaltdavid commented on src/App.vue
> +			>
Indentation.

2020-04-04 03:28 UTC, ctrlaltdavid commented on src/App.vue
> +            // This function also auto-installs interface.
```suggestion
            // This function also auto-installs Interface.
```

2020-04-04 03:32 UTC, ctrlaltdavid commented
Note: There are other files still containing "Athena", plus the execuables' icons need updating.

2020-04-10 08:41 UTC, ctrlaltdavid approved these changes

2020-04-10 09:06 UTC, merged

2020-04-10 09:07 UTC, kasenvr commented
I'm thinking we want to disable the launch button while an installation is running, I know the launcher is far more powerful (the ability to have multiple interfaces) but the sake of ease of use for the timebeing for such a trade off does not seem so bad.